# Generated by Django 6.0.1 on 2026-01-18 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Post', max_length=32, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publish Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Write Time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post', verbose_name='Post')),
            ],
        ),
    ]
